# Generated by Django 6.0.5 on 2026-05-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_date_of_birth_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('', 'Prefer not to say')], default='', max_length=10),
        ),
    ]
