# Generated by Django 6.0.4 on 2026-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_slug_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='require_resources',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='require_video',
            field=models.BooleanField(default=False),
        ),
    ]
