# Generated by Django 6.0.5 on 2026-05-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_require_resources_lesson_require_video'),
    ]

    operations = [
    ]
