# Generated by Django 6.0.4 on 2026-05-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quizquestion_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='drip_delay_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after enrollment when this module becomes available'),
        ),
    ]
