# Generated by Django 6.0.4 on 2026-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_module_drip_delay_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
