# Generated by Django 6.0.5 on 2026-05-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_end_date_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Manually lock this lesson for all learners'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Manually lock this module for all learners'),
        ),
    ]
