# Generated by Django 6.0.5 on 2026-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_is_locked_module_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Specific date and time when this module becomes available for everyone', null=True),
        ),
    ]
