# Generated by Django 6.0.4 on 2026-05-19 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_module_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='lessons/resources/')),
                ('content', models.TextField(blank=True, help_text='Markdown content if file is not used')),
                ('resource_type', models.CharField(choices=[('markdown', 'Markdown Notes'), ('pdf', 'PDF Document'), ('zip', 'ZIP Archive'), ('other', 'Other Resource')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
