# Generated by Django 6.0.4 on 2026-05-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='discussion', help_text='discussion, issue, project', max_length=50),
        ),
    ]
